#!/bin/bash

# =;eth0;IPv4;puavo;SSH-Fernzugriff;local;puavo-builder.local;192.168.1.112;22;"update_status=download 80" "hosttype=laptop"
# 1 2    3    4     5               6     7                   8             9  10



#!/bin/sh

red='\033[0;31m'
yellow='\033[0;33m'
green='\033[0;32m'
nc='\033[0m' # No Color 


doit(){
    IP=$1
    shift
    while [ $# -gt 0 ]; do
	ARG=$(echo "$1"|sed -e "s/\"//g")
	case "$ARG" in
	    hostname*)
		HOSTNAME=$(echo "$ARG"|cut -d= -f2)
	        ;;
	    hosttype*)
		TYPE=$(echo "$ARG"|cut -d= -f2)
		case "$TYPE" in
		    wirelessaccesspoint)
			HOSTTYPE="accesspoint"
			;;
		    laptop)
			HOSTTYPE="laptop     "
			;;
		    fatclient)
			HOSTTYPE="fatclient  "  
			;;
                    *)
			HOSTTYPE="unbekannt  "
			;;
		esac
	        ;;
	    boottime*)
		BOOTTIME=$(echo "$ARG"|cut -d= -f2)
	        ;;
	    lastseen*)
		LASTSEEN=$(echo "$ARG"|cut -d= -f2)
	        ;;
	    current*)
		CURRENT=$(echo "$ARG"|cut -d= -f2|sed -e "s/.img//g")
	        ;;
	    preferred*)
		PREFERRED=$(echo "$ARG"|cut -d= -f2|sed -e "s/.img//g")
	        ;;
	    update*)
		UPDATE=$(echo "$ARG"|cut -d= -f2|sed -e "s/.img//g")
	        ;;
	    *)
                ;;
	esac
	shift
    done

    UPTIME=$(( "$(date +%s)" - "$BOOTTIME" ))
    UPSTRING=$(printf "%10s" "$UPTIME")
    NAME=$(printf "%-20s" "$HOSTNAME")
    IPSTR=$(printf "%-15s" "$IP")    

    if test "$CURRENT" != "$PREFERRED"; then
	case $UPDATE in
	    $PREFERRED:finished:100)
		color=$green
		;;
	    *:finished:100)
		color=$yellow
		;;
	    *)
		color=$red
		;;
	esac
    else
	color=$nc
    fi
    echo -e "$color$NAME\t$HOSTTYPE\t$IPSTR\t$UPSTRING\t$CURRENT\t$UPDATE$nc"
}


printf "HOSTNAME         \tHOSTTYPE       \tIP      \t    UPTIME\tCURRENT                                      \tUPDATE\n"

avahi-browse -artp 2>/dev/null|grep "=;.*;IPv4;puavo;"|cut -d";" -f8,10|sed -e"s/;/ /g"| while read -r line; do
    doit $line
done


exit
