#!/bin/sh



echo "setting up safesearch"
    
if cat /etc/hosts|grep -q -v www.google.com; then

    cat << EOF >> /etc/hosts
#
# force safesaerch for google
216.239.38.120 www.google.com www.google.ad www.google.ae www.google.com.af www.google.com.ag
216.239.38.120 www.google.com.ai www.google.al www.google.am www.google.co.ao www.google.com.ar
216.239.38.120 www.google.as www.google.at www.google.com.au www.google.az www.google.ba www.google.com.bd
216.239.38.120 www.google.be www.google.bf www.google.bg www.google.com.bh www.google.bi www.google.bj
216.239.38.120 www.google.com.bn www.google.com.bo www.google.com.br www.google.bs www.google.bt
216.239.38.120 www.google.co.bw www.google.by www.google.com.bz www.google.ca www.google.cd www.google.cf
216.239.38.120 www.google.cg www.google.ch www.google.ci www.google.co.ck www.google.cl www.google.cm
216.239.38.120 www.google.cn www.google.com.co www.google.co.cr www.google.com.cu www.google.cv
216.239.38.120 www.google.com.cy www.google.cz www.google.de www.google.dj www.google.dk www.google.dm
216.239.38.120 www.google.com.do www.google.dz www.google.com.ec www.google.ee www.google.com.eg
216.239.38.120 www.google.es www.google.com.et www.google.fi www.google.com.fj www.google.fm www.google.fr
216.239.38.120 www.google.ga www.google.ge www.google.gg www.google.com.gh www.google.com.gi www.google.gl
216.239.38.120 www.google.gm www.google.gp www.google.gr www.google.com.gt www.google.gy www.google.com.hk
216.239.38.120 www.google.hn www.google.hr www.google.ht www.google.hu www.google.co.id www.google.ie
216.239.38.120 www.google.co.il www.google.im www.google.co.in www.google.iq www.google.is www.google.it
216.239.38.120 www.google.je www.google.com.jm www.google.jo www.google.co.jp www.google.co.ke
216.239.38.120 www.google.com.kh www.google.ki www.google.kg www.google.co.kr www.google.com.kw
216.239.38.120 www.google.kz www.google.la www.google.com.lb www.google.li www.google.lk www.google.co.ls
216.239.38.120 www.google.lt www.google.lu www.google.lv www.google.com.ly www.google.co.ma www.google.md
216.239.38.120 www.google.me www.google.mg www.google.mk www.google.ml www.google.com.mm www.google.mn
216.239.38.120 www.google.ms www.google.com.mt www.google.mu www.google.mv www.google.mw www.google.com.mx
216.239.38.120 www.google.com.my www.google.co.mz www.google.com.na www.google.com.nf www.google.com.ng
216.239.38.120 www.google.com.ni www.google.ne www.google.nl www.google.no www.google.com.np www.google.nr
216.239.38.120 www.google.nu www.google.co.nz www.google.com.om www.google.com.pa www.google.com.pe
216.239.38.120 www.google.com.pg www.google.com.ph www.google.com.pk www.google.pl www.google.pn
216.239.38.120 www.google.com.pr www.google.ps www.google.pt www.google.com.py www.google.com.qa
216.239.38.120 www.google.ro www.google.ru www.google.rw www.google.com.sa www.google.com.sb www.google.sc
216.239.38.120 www.google.se www.google.com.sg www.google.sh www.google.si www.google.sk www.google.com.sl
216.239.38.120 www.google.sn www.google.so www.google.sm www.google.sr www.google.st www.google.com.sv
216.239.38.120 www.google.td www.google.tg www.google.co.th www.google.com.tj www.google.tk www.google.tl
216.239.38.120 www.google.tm www.google.tn www.google.to www.google.com.tr www.google.tt www.google.com.tw
216.239.38.120 www.google.co.tz www.google.com.ua www.google.co.ug www.google.co.uk www.google.com.uy
216.239.38.120 www.google.co.uz www.google.com.vc www.google.co.ve www.google.vg www.google.co.vi
216.239.38.120 www.google.com.vn www.google.vu www.google.ws www.google.rs www.google.co.za
216.239.38.120 www.google.co.zm www.google.co.zw www.google.cat
# force youtube strikt
#78.41.204.29 www.youtube.com
#78.41.204.29 m.youtube.com
#78.41.204.29 youtubei.googleapis.com
#78.41.204.29 youtube.googleapis.com
#78.41.204.29 www.youtube-nocookie.com
# force bing strikt
204.79.197.220 www.bing.com bing.com
# force safesearch duckduckgo
176.34.131.233 duckduckgo.com www.duckduckgo.com
EOF

fi


exit 0


