#!/bin/sh



finish(){
    test -n "$(which puavomenu-moreapps)"  &&  puavomenu-moreapps
    test -n "$(which puavomenu-reload)" &&  puavomenu-reload  
}


# may it shlod not run on peronaly administered hosts?
ADMIN=$(puavo-conf puavo.admin.personally_administered)

HOSTTYPE=$(puavo-conf puavo.hosttype)
test "$HOSTTYPE" = "fatclient" && sleep 999999999999999999999999
test -d /images/ ||  sleep 99999999999999999999999999

finish

sleep 120

while true; do
	puavo-pkg-update
        finish
    sleep 3600
done

#never come here!
exit 0


