#!/bin/sh

device="wg0"

get_my_address(){
#    echo get_my_adress
    url=$(puavo-conf puavo.wg.restapi.url)
    key=$(puavo-conf puavo.wg.restapi.key)
    school=$(puavo-conf puavo.wg.network.name)
    hostname=$(cat /etc/puavo/hostname)
    addr=""

    erfolg=false    
    until $erfolg; do
	nm-online -q -t 3600

        my_address=$(curl -s --get --data-urlencode "apikey=$key" --data-urlencode "publickey=$my_publickey" $url/$school/$hostname)  


	if test -n "$my_address"; then
	    erfolg=true
	else
	    echo sleep
	    sleep 10
	fi	
    done
}

link_down(){
    ip link|grep -q $device && ip link del $device
}


############ main #########################

#trap link_down EXIT HUP INT QUIT KILL TERM


#peer
endpoint=$(puavo-conf puavo.wg.peer.endpoint)
publickey=$(puavo-conf puavo.wg.peer.publickey)
presharedkey=$(puavo-conf puavo.wg.peer.preshared)
allowedips=$(puavo-conf puavo.wg.peer.allowedips)
subnetmask=$(puavo-conf puavo.wg.network.netmask)

#echo puavo-conf $endpoint -  $publickey # - $presharedkey - $allowedips -

test -n "$endpoint" || exit 0
test -n "$publickey" || exit 0
#test -n "$presharedkey" || exit 0
test -n "$allowedips" || exit 0
test -n "$subnetmask" || exit 0

my_privatekey=$(wg genkey)
echo $my_privatekey > /tmp/private.key
my_publickey=$(echo $my_privatekey|wg pubkey)

#echo "my_keys: $my_privatekey $my_publickey"

get_my_address

test -n "$my_address" || exit 1

link_down

#echo "configure...."
ip link add dev $device type wireguard; 
ip address add dev $device $my_address/$subnetmask; 
ip link set multicast on dev $device;

# maybe: private-key <(echo "$privatekey")

wg set $device\
   private-key /tmp/private.key\
   peer $publickey\
   endpoint $endpoint\
   allowed-ips $allowedips\
   persistent-keepalive 25

rm /tmp/private.key


ip link set $device up; 
#ip route add $allowedips dev $device;

echo "link is up"


exit 0
