#!/bin/sh

PORT=3000

if test "$(puavo-conf puavo.clientapi.enable 2>/dev/null)" = "true"; then

    URL="$(puavo-conf puavo.clientapi.url)";
    if test -z "$URL"; then
        SERVER="$(/usr/lib/puavo-ltsp-client/lookup-imageserver-by-dns| cut -d: -f1)"
	if test -n "$SERVER"; then
	    URL="ws://${SERVER}:${PORT}"
	fi
    fi
    
    if test -n "$URL"; then
        HOSTTYPE="$(puavo-conf puavo.hosttype)"
	HOSTNAME="$(hostname)"
	IMAGE="$(cat /etc/puavo-image/name)"
	RELEASE="$(cate /etc/puavo-image/release)"
	case "$HOSTTYPE" in
	    bootserver)
		mkdir -p /var/log/clientapi
		touch /var/log/clientapi/clients.json
		if ! test -f /var/log/clientapi/updateinfo.json; then
		    echo "{}" > /var/log/clientapi/updateinfo.json
		fi
		echo "info: start server ..."
		cd /opt/clientapi/
		node server.js "$PORT"
		;;
	    laptop|fatclient)
		echo "info: start client ..."
		cd /opt/clientapi
		node client.js "$URL" "$HOSTNAME" "$HOSTTYPE" "$IMAGE" "$RELEASE" 
		;;
	    *)
		echo "info: not running on $HOSTTYPE. sleeping ..."
		sleep infinity
		;;
	esac
    else
	echo "info: no puavobox. sleeping ..."
	sleep infinity
    fi    
else
    echo "info: not enabled. sleeping ..."
    sleep infinity
fi

