#!/bin/sh

hosttype=$(puavo-conf puavo.hosttype)
list=$(puavo-conf puavo.profiles.list)


#publish host on avahi
cat <<EOF > /etc/avahi/services/puavo-avahi-publish.service
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
<name replace-wildcards="yes">puavo $hosttype %h $list</name>
<service>
<type>_ssh._tcp</type>
<port>22</port>
</service>
</service-group>
EOF
systemctl restart avahi-daemon.service

test $(uname -r | cut -d. -f1) = 5 || exit 0 
command -v wg 2>&1 >/dev/null || exit 0 

case $hosttype in
    bootserver)
	systemctl start puavo-virtualltsp-daemon
	;;
    laptop|wirelessaccesspoint)
	/usr/local/sbin/puavo-virtualltsp-client
	;;
    *)
	exit 0
	;;
esac

    
