#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# https://git.zx2c4.com/wireguard-tools/plain/contrib/ncat-client-server/client.sh
#
# Copyright (C) 2015-2020 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.

#server="192.168.1.139"
#server="demo.wireguard.com"


case $(puavo-conf puavo.hosttype) in
    bootserver)
	exit 1
	;;
    *)
	;;
esac


if [ "$1" == "stop" ]; then
    ip link delete dev wg0
    echo "nameserver 127.0.0.1" > /etc/resolv.conf
    exit 0
fi

for I in $(seq 10);do
   #test -e /usr/local/bin/puavo-find-puavobox && exit 0                                                              
   echo -n "$I "
   puavobox="$(puavo-find-puavobox)"
   sleep 1
   test -n "$puavobox" && break
done

echo "Puavbox: *$puavobox*"

test -n "$puavobox" || exit 1


set -e
[[ $UID == 0 ]] || { echo "You must be root to run this."; exit 1; }
exec 3<>/dev/tcp/$puavobox/42912
privatekey="$(wg genkey)"

pubkey=$(wg pubkey <<<"$privatekey") 
echo "$pubkey:$(hostname)"              >&3  
#echo "$pubkey:$(hostname)"

IFS=: read -r status server_pubkey server_port internal_ip <&3
echo $status
[[ $status == OK ]]
ip link del dev wg0 2>/dev/null || true
ip link add dev wg0 type wireguard
wg set wg0 private-key <(echo "$privatekey") peer "$server_pubkey" allowed-ips 0.0.0.0/0 endpoint "$puavobox:$server_port" persistent-keepalive 25
ip address add "$internal_ip"/20 dev wg0
ip link set up dev wg0

echo "nameserver 10.249.15.254" > /etc/resolv.conf
echo "nameserver 127.0.0.1" >> /etc/resolv.conf

exit 0
