#!/bin/bash


find_puavobox(){
    echo "$(avahi-browse -artpk| grep "=;.*;IPv4;puavo.*bootserver" | cut -d";" -f8|head -n1)"
}


# no bootservers
test "$(puavo-conf puavo.hosttype)" = "bootserver" && sleep 9999999999999999999999999

nm-online -q -t 3600

puavobox=$(puavo-conf puavo.puavobox 2>/dev/null)
case "$puavobox" in
    "")
	sleep 9999999999999999999999
	;;
    0.0.0.0)
        while test "$puavobox" = "0.0.0.0"; do
             $puavobox=$(find_puavobox)
             test "$puavobox" = "10.249.15.254" && sleep 999999999999999999999999
             sleep 5
	done	
	;;
    *)
	;;
esac

# is it realy a puavo box?
host cups $puavobox 2>&1 >/dev/null || sleep 9999999999999999999999999

#while ip route | grep -v -q default; do sleep 1; done

while true; do
    if nm-online -q -t 3600; then
	if ip route | grep -q "10.249.0.0/20";then
	    true
	else
	    sleep 2
	    # here the work is done 
            echo ip route add 10.249.0.0/20 via $puavobox
	    ip route add 10.249.0.0/20 via $puavobox
            echo "nameserver $puavobox" > /etc/resolv.conf
        fi
        sleep 30
    fi
done

exit 
