#!/bin/sh

CHROOT=$1

if test -n "$CHROOT";then
    test -d $CHROOT || exit 1
else
    echo "usage puavo-dir-patch (CHROOT)DIR"
    exit 1
fi

#copy chroot binary to chroot






cat << 'EOF'  > $CHROOT/usr/local/bin/puavo-chroot-apply
#!/bin/sh

echo "**************************************************************" 1>&2
echo "*                                                            *" 1>&2
echo "*                     Hello Chroot                           *" 1>&2
echo "*                                                            *" 1>&2
echo "**************************************************************" 1>&2
UPDATED=1
ERROR=0

CHECKLIST=""


echo " " > /etc/puavo-image/debs.list
echo " " > /etc/puavo-image/parts.list


check(){
    if test $? = 0;then
        echo "  ok"
    else
        CHECKLIST="$CHECKLIST $1"
	echo "  error!"
	ERROR=1
    fi
}

#bin
if test -d /install/bin.d;then
    if test -n "$(ls /install/bin.d|grep .sh)";then
        echo "**************************************************************" 1>&2
        echo "                          bin                                *" 1>&2
        echo "**************************************************************" 1>&2
        for B in $(ls /install/bin.d);do
	    if test -x /install/bin.d/$B;then
                echo -n $B                                                    1>&2
		/install/bin.d/$B
		check  $B                                                       1>&2
	    fi 
        done
    fi
fi

#files
if test -d /install/files.d;then
    if test -n "$(ls /install/files.d/)";then
	echo "**************************************************************" 1>&2
        echo "                         files                               *" 1>&2
        echo "**************************************************************" 1>&2
        cp -r /install/files.d/* /
        echo "ok"                                                             1>&2
    fi
fi


#lists
if test -d /install/lists.d;then
    LISTS="$(ls /install/lists.d|grep .list|grep -v off|xargs)"
    if test -n "$LISTS";then
        echo "**************************************************************" 1>&2
        echo "                         lists                               *" 1>&2
        echo "**************************************************************" 1>&2
        echo "$LISTS :"							      1>&2
        apt-get update
	UPDATED=0
        PAKS=""
        for L in $LISTS;do
            PAKS="$PAKS $(cat /install/lists.d/$L|xargs) "
        done
        echo $PAKS | fmt                                                      1>&2
        apt-get -y install $PAKS
	check  "lists"                                                        1>&2
    fi

fi

#debs
if test -d /install/debs.d;then
    if test -n "$(ls /install/debs.d|grep .deb)";then
        echo "**************************************************************" 1>&2
        echo "                         debs                                *" 1>&2
        echo "**************************************************************" 1>&2
        for D in $(ls /install/debs.d/*.deb);do
             echo $(basename $D)                                              1>&2

             echo "$D " >> /etc/puavo-image/debs.list

             dpkg -i $D
             #check
        done
        if test $UPDATED = 1;then
	    apt-get update
	    UPDATED=0
	fi
        echo -n "*debs  dependencies*"                                         1>&2
	apt-get -y -f install
	check "*debs dependencies*"                                            1>&2
    fi
fi

#parts
if test -d /install/parts.d;then
    if test -n "$(ls /install/parts.d/)";then
        echo "**************************************************************" 1>&2
        echo "                         parts                               *" 1>&2
        echo "**************************************************************" 1>&2
	if test $UPDATED = 1;then
	    apt-get update
	fi
        for P in $(ls /install/parts.d/);do
            if test -x /install/parts.d/$P/install.sh;then
                 echo -n $P                                                   1>&2

                 echo "$P " >> /etc/puavo-image/parts.list


                 /install/parts.d/$P/install.sh
  	         check $P                                                     1>&2
            fi
        done
        echo -n "*parts dependencies*"                                           1>&2
	apt-get -y -f install
	check "*parts dependencies*"                                          1>&2
    fi
fi

echo "**************************************************************" 1>&2
echo "*                                                            *" 1>&2
echo "*                     Goodbye Chroot                         *" 1>&2
echo "*                                                            *" 1>&2
echo "**************************************************************" 1>&2
echo                                                                  1>&2

if test $ERROR = 0;then
    echo "info: chroot ends successfully"                             1>&2
else
    echo "error(s) occurred in:"                                      1>&2
    echo $CHECKLIST|fmt                                               1>&2
fi
echo                                                                  1>&2

#echo                                                                  1>&2
#echo "**************************************************************" 1>&2
#echo "**************************************************************" 1>&2

exit $ERROR
EOF
chmod +x $CHROOT/usr/local/bin/puavo-chroot-apply


echo "*********************************************333"
cat /usr/local/bin/puavo-chroot-apply
echo "*********************************************333"

if test $CHROOT = "/";then
    /usr/local/bin/puavo-chroot-apply
else
    echo "/usr/local/bin/puavo-chroot-apply" | puavo-dir-chroot $CHROOT  
fi

exit $?

	
