#!/bin/sh

if test -z "$1" -o "$1" = "-h" -o "$1" = "--help";then
    echo "usage: puavo-img-repo  IMAGE_DIR [MIRROR_DIR]"
    echo
    echo "       Maintains an image repository of all images from IMAGE_DIR"
    echo "       in MIRROR_DIR. When MIRROR_DIR is not set it defaults to"
    echo "       IMAGE_DIR/mirror ."
    exit 0
fi


IMAGE_DIR="$1"
if ! test -d $IMAGE_DIR;then
    echo "error: IMAGEDIR \"$IMAGE_DIR\" not found"
    exit 1
fi
IMAGE_DIR=$(realpath $IMAGE_DIR)

if test -z "$2";then
    MIRROR_DIR="$IMAGE_DIR/mirror"
else
    MIRROR_DIR=$(realpath $2)
fi

list_images(){
if test -e $IMAGE_DIR/images.json;then
    cat $IMAGE_DIR/images.json
    return 0
fi
SERIES=""
for I in $(find $IMAGE_DIR -maxdepth 1 -name '*-os-*-20*-amd64\.img'); do
    OSNAME=$(basename ${I}|cut -d- -f1)
    CLASS=$(basename {$I}|cut -d- -f3)
    DIST=$(basename ${I}|cut -d- -f4)

    S="$OSNAME-os-$CLASS-$DIST"
    if ! echo "$SERIES"|grep -q ${S};then
	SERIES="${SERIES} ${S}"
    fi
done
#echo $SERIES
echo "{" 
FIRST_S="0"
for S in $(echo ${SERIES});do
    if test $FIRST_S = 0 ;then
	FIRST_S=1
    else
	echo "," 
    fi    
    echo "  \"${S}-amd64\": [" 
    FIRST_I="0"
    SEARCH="${S}-20*-amd64\.img"
    for I in $(find $IMAGE_DIR  -maxdepth 1 -name "$SEARCH");do
        if test $FIRST_I = 0 ;then
  	    FIRST_I=1
        else
	    echo "," 
        fi
	echo -n "    \"$(basename ${I})\""
    done
    echo
    echo -n " ]" 
done
echo
echo "}" 
}

#list_images
#exit

# make images.json
test -d $IMAGE_DIR/.puavo-os || mkdir -p $IMAGE_DIR/.puavo-os
list_images > $IMAGE_DIR/.puavo-os/images.json

# call make
test -d $MIRROR_DIR/.checksums || mkdir -p $MIRROR_DIR/.checksums
test -d $MIRROR_DIR/.signatures || mkdir -p $MIRROR_DIR/.signatures
test -d $MIRROR_DIR/meta || mkdir -p $MIRROR_DIR/meta
test -d $MIRROR_DIR/rdiffs || mkdir -p $MIRROR_DIR/rdiffs
cd ${IMAGE_DIR}/.puavo-os


#needs absolute paths!!!!!!!!!!!!
sudo /puavo-os/.aux/make-rdiffs \
        image_dir="${IMAGE_DIR}" \
	images_urlbase="https://cdn.puavo.org" \
	mirror_dir="${MIRROR_DIR}" \
	mode="production" 


# fix permissions
sudo chown --recursive --reference ${IMAGE_DIR}  ${IMAGE_DIR}/.puavo-os
sudo chown --recursive --reference ${IMAGE_DIR}  ${MIRROR_DIR}

exit



