#!/bin/sh


HOSTTYPE="$(puavo-conf puavo.hosttype)"
test "$HOSTTYPE" = "bootserver" && exit 0
                                                                                                                                             

DIST=$(cat /etc/puavo-image/name|cut -d- -f4)
puavo-conf puavo.support.image_changelog_url  http://changelog.opinsys.fi/de/opinsys/$DIST/


echo "setting up webfilter"


#################### hosts ###########################


if ! test -f /etc/hosts.ori; then cp /etc/hosts /etc/hosts.ori; fi

cat /etc/hosts.ori > /etc/hosts.tmp

if ! test  "$(puavo-conf puavo.webfilter.safesearch 2>/dev/null)" = "false"; then
    echo "set safesearch"
    cat << EOF >> /etc/hosts.tmp
#
# force safesaerch for google
216.239.38.120 www.google.com www.google.ad www.google.ae www.google.com.af www.google.com.ag
216.239.38.120 www.google.com.ai www.google.al www.google.am www.google.co.ao www.google.com.ar
216.239.38.120 www.google.as www.google.at www.google.com.au www.google.az www.google.ba www.google.com.bd
216.239.38.120 www.google.be www.google.bf www.google.bg www.google.com.bh www.google.bi www.google.bj
216.239.38.120 www.google.com.bn www.google.com.bo www.google.com.br www.google.bs www.google.bt
216.239.38.120 www.google.co.bw www.google.by www.google.com.bz www.google.ca www.google.cd www.google.cf
216.239.38.120 www.google.cg www.google.ch www.google.ci www.google.co.ck www.google.cl www.google.cm
216.239.38.120 www.google.cn www.google.com.co www.google.co.cr www.google.com.cu www.google.cv
216.239.38.120 www.google.com.cy www.google.cz www.google.de www.google.dj www.google.dk www.google.dm
216.239.38.120 www.google.com.do www.google.dz www.google.com.ec www.google.ee www.google.com.eg
216.239.38.120 www.google.es www.google.com.et www.google.fi www.google.com.fj www.google.fm www.google.fr
216.239.38.120 www.google.ga www.google.ge www.google.gg www.google.com.gh www.google.com.gi www.google.gl
216.239.38.120 www.google.gm www.google.gp www.google.gr www.google.com.gt www.google.gy www.google.com.hk
216.239.38.120 www.google.hn www.google.hr www.google.ht www.google.hu www.google.co.id www.google.ie
216.239.38.120 www.google.co.il www.google.im www.google.co.in www.google.iq www.google.is www.google.it
216.239.38.120 www.google.je www.google.com.jm www.google.jo www.google.co.jp www.google.co.ke
216.239.38.120 www.google.com.kh www.google.ki www.google.kg www.google.co.kr www.google.com.kw
216.239.38.120 www.google.kz www.google.la www.google.com.lb www.google.li www.google.lk www.google.co.ls
216.239.38.120 www.google.lt www.google.lu www.google.lv www.google.com.ly www.google.co.ma www.google.md
216.239.38.120 www.google.me www.google.mg www.google.mk www.google.ml www.google.com.mm www.google.mn
216.239.38.120 www.google.ms www.google.com.mt www.google.mu www.google.mv www.google.mw www.google.com.mx
216.239.38.120 www.google.com.my www.google.co.mz www.google.com.na www.google.com.nf www.google.com.ng
216.239.38.120 www.google.com.ni www.google.ne www.google.nl www.google.no www.google.com.np www.google.nr
216.239.38.120 www.google.nu www.google.co.nz www.google.com.om www.google.com.pa www.google.com.pe
216.239.38.120 www.google.com.pg www.google.com.ph www.google.com.pk www.google.pl www.google.pn
216.239.38.120 www.google.com.pr www.google.ps www.google.pt www.google.com.py www.google.com.qa
216.239.38.120 www.google.ro www.google.ru www.google.rw www.google.com.sa www.google.com.sb www.google.sc
216.239.38.120 www.google.se www.google.com.sg www.google.sh www.google.si www.google.sk www.google.com.sl
216.239.38.120 www.google.sn www.google.so www.google.sm www.google.sr www.google.st www.google.com.sv
216.239.38.120 www.google.td www.google.tg www.google.co.th www.google.com.tj www.google.tk www.google.tl
216.239.38.120 www.google.tm www.google.tn www.google.to www.google.com.tr www.google.tt www.google.com.tw
216.239.38.120 www.google.co.tz www.google.com.ua www.google.co.ug www.google.co.uk www.google.com.uy
216.239.38.120 www.google.co.uz www.google.com.vc www.google.co.ve www.google.vg www.google.co.vi
216.239.38.120 www.google.com.vn www.google.vu www.google.ws www.google.rs www.google.co.za
216.239.38.120 www.google.co.zm www.google.co.zw www.google.cat
# force bing strikt
204.79.197.220 www.bing.com bing.com
# force safesearch duckduckgo
176.34.131.233 duckduckgo.com www.duckduckgo.com
EOF
fi

SAFETUBE=$(puavo-conf puavo.webfilter.safetube 2>/dev/null)

case "$SAFETUBE" in
    *strikt|true)
	IP="216.239.38.120"
    ;;
    moderate)
	IP="216.239.38.119"
    ;;
    *)
	IP=""
    ;;
esac
 
if test -n "$IP"; then
    echo "set youtube strikt"
    cat <<EOF >> /etc/hosts.tmp
#
#restrict.youtube.com has address 216.239.38.120
#restrictmoderate.youtube.com has address 216.239.38.119
# war 78.41.204.29
# force youtube strikt
$IP www.youtube.com
$IP m.youtube.com
$IP youtubei.googleapis.com
$IP youtube.googleapis.com
$IP www.youtube-nocookie.com
EOF
fi

mv /etc/hosts.tmp /etc/hosts


#################### resolv.conf ###########################

if ! test "$(puavo-conf puavo.webfilter.enable 2>/dev/null)" = "true";then
    echo "dnsprovider not enabled,exit"
    if test -f /etc/resolv.conf.ori;then
	cp /etc/resolv.conf.ori /etc/resolv.conf
    fi
    
    exit 0
fi


#do not activate in school

#only on laptops
if test "$HOSTTYPE" != "laptop";then
    echo "not laptop, exit"
    exit 0
fi

echo "ok, laptop"
# with puavobox exit
if test -n "$(/usr/lib/puavo-ltsp-client/lookup-image-server-by-dns)"; then
    echo "see puavobox, exit"
fi

#exclude schoolnet
GATEWAY=$(ip route |grep default|cut -d" " -f3)
SCHOOLNET=$(puavo-conf puavo.webfilter.schoolnet 2>/dev/null|cut -d/ -f1)
if test -n "$SCHOOLNET";then
    if test "$SCHOOLNET" = "$GATEWAY"; then
	echo "see schoolnet, exit"
	exit 0
    fi
fi


PROVIDER="$(puavo-conf puavo.webfilter.dnsprovider 2>/dev/null)"

if test "$PROVIDER" = "none";then
    echo "provider set to none,exit"
    exit 0
fi


test -n "$PROVIDER" || PROVIDER="cloudflare-family" 

echo "set dnsprovider $PROVIDER"

case "$PROVIDER" in
    cloudflare)
	DNS1="1.1.1.1"
	DNS2="1.0.0.1"
    ;;
    cloudflare-security)
	DNS1="1.1.1.2"
	DNS2="1.0.0.2"
    ;;
    cloudflare-family)
	DNS1="1.1.1.3"
	DNS2="1.0.0.3"
    ;;    
    google)
	DNS1="8.8.8.8"
	DNS2="8.8.4.4"
    ;;
    quad9)
	DNS1="9.9.9.9"
	DNS2="149.112.112.112"
    ;;
    cleanbrowsing)
	DNS1="185.228.168.9"
	DNS2="185.228.169.9"
    ;;
    cleanbrowsing-family)
	DNS1="185.228.168.168"	
	DNS2="185.228.169.168"
    ;;
    cleanbrowsing-adult)
	DNS1="185.228.168.10"
	DNS2="185.228.169.11"
    ;;
    adguard-nofilter|adguard-nonfiltering)
	DNS1="94.140.14.140"
	DNS2="94.140.14.141"
    ;;
    adguard)
	DNS1="94.140.14.14"
	DNS2="94.140.15.15"
    ;;
    adguard-family)
	DNS1="94.140.14.15"
	DNS2="94.140.15.16"
    ;;
    opendns)
	DNS1="208.67.222.222"
	DNS2="208.67.220.220"
    ;;
    opendns-family)
	DNS1="208.67.222.123"
	DNS2="208.67.220.123"
    ;;
    *)
	PROVIDER="provider $PROVIDER not found, using quad9 as fallback"
	DNS1="9.9.9.9"
	DNS2="149.112.112.112"
    ;;
esac
    
if ! test -f /etc/resolv.conf.ori; then cp /etc/resolv.conf /etc/resolv.conf.ori; fi

OLD="$(cat /etc/resolv.conf.ori)"
echo "# dns provider: $PROVIDER"  >  /etc/resolv.conf 
echo "nameserver $DNS1"          >>  /etc/resolv.conf
#echo "nameserver $DNS2"          >> /etc/resolv.conf
echo "$OLD"                      >> /etc/resolv.conf

echo "done" 
 
exit 0


